# Generated by Django 3.0.8 on 2020-09-01 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='These are code!', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+$', 'Problem code must be ^[a-z0-9]+$')], verbose_name='problem code')),
                ('name', models.CharField(db_index=True, help_text='These are full name of the problem', max_length=100, verbose_name='problem name')),
                ('description', models.TextField(verbose_name='problem Description')),
                ('partial', models.BooleanField(verbose_name='allows partial points')),
                ('is_full_markup', models.BooleanField(default=False, verbose_name='allow full markdown access')),
            ],
            options={
                'verbose_name': 'problem',
                'permissions': (('see_problem', 'See problmes'), ('edit_problem', 'Edit problems'), ('clone_problem', 'Colne problem')),
            },
        ),
    ]
