# Generated by Django 3.0.8 on 2020-09-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='partial',
        ),
    ]
