# Generated by Django 3.0.8 on 2020-09-02 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_remove_problem_partial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'problem'},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_full_markup',
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.PositiveIntegerField(default=0, help_text='The memory limit for this problem, in kilobytes (e.g. 64mb = 65536 kilobytes).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1048576)], verbose_name='memory limit'),
        ),
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.FloatField(default=0, help_text="Points awarded for problem completion. Points are displayed with a 'p' suffix if partial.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='points'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.FloatField(default=0, help_text='The time limit for this problem, in seconds. Fractional seconds (e.g. 1.5) are supported.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='time limit'),
        ),
    ]
